version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-portfolio
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: always
